# Generated by Django 4.2.6 on 2023-10-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ena_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ena.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ena_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ena.sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('accession', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('results_dir', models.CharField(max_length=100)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyses.study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
