# Generated by Django 5.0.1 on 2024-02-26 17:18
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models

import analyses.base_models.mgnify_accessioned_models
import analyses.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ena", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "accession",
                    models.GeneratedField(
                        db_index=True,
                        db_persist=True,
                        expression=analyses.base_models.mgnify_accessioned_models.ConcatOp(
                            models.Value("MGYA"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    models.F("id"), models.CharField()
                                ),
                                7,
                                models.Value("0"),
                            ),
                        ),
                        output_field=models.CharField(max_length=20),
                    ),
                ),
                ("is_ready", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "webin_submitter",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("results_dir", models.CharField(max_length=100)),
                (
                    "annotations",
                    models.JSONField(
                        default=analyses.models.Analysis.default_annotations
                    ),
                ),
                (
                    "ena_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ena.study"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnalysedContig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contig_id", models.CharField(max_length=255)),
                ("coverage", models.FloatField()),
                ("length", models.IntegerField()),
                (
                    "annotations",
                    models.JSONField(
                        default=analyses.models.AnalysedContig.default_annotations
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.analysis",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                (
                    "webin_submitter",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("ena_accessions", models.JSONField(db_index=True, default=list)),
                ("is_suppressed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dir", models.CharField(max_length=200)),
                (
                    "ena_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ena.study"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "accession",
                    models.GeneratedField(
                        db_index=True,
                        db_persist=True,
                        expression=analyses.base_models.mgnify_accessioned_models.ConcatOp(
                            models.Value("MGYN"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    models.F("id"), models.CharField()
                                ),
                                7,
                                models.Value("0"),
                            ),
                        ),
                        output_field=models.CharField(max_length=20),
                    ),
                ),
                ("is_ready", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "webin_submitter",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("ena_accessions", models.JSONField(db_index=True, default=list)),
                ("is_suppressed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ena_sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ena.sample"
                    ),
                ),
                (
                    "ena_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ena.study"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="analyses.sample",
            ),
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "accession",
                    models.GeneratedField(
                        db_index=True,
                        db_persist=True,
                        expression=analyses.base_models.mgnify_accessioned_models.ConcatOp(
                            models.Value("MGYS"),
                            django.db.models.functions.text.LPad(
                                django.db.models.functions.comparison.Cast(
                                    models.F("id"), models.CharField()
                                ),
                                7,
                                models.Value("0"),
                            ),
                        ),
                        output_field=models.CharField(max_length=20),
                    ),
                ),
                ("is_ready", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "webin_submitter",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("ena_accessions", models.JSONField(db_index=True, default=list)),
                ("is_suppressed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "ena_study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ena.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssemblyAnalysisRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requestor", models.CharField(max_length=20)),
                (
                    "status",
                    models.JSONField(
                        blank=True,
                        default=analyses.models.AssemblyAnalysisRequest.AssemblyAnalysisStates.default_status,
                        null=True,
                    ),
                ),
                (
                    "request_metadata",
                    models.JSONField(
                        blank=True,
                        default=analyses.models.AssemblyAnalysisRequest.RequestMetadata.default_metadata,
                        null=True,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analyses.study"
            ),
        ),
    ]
