# Generated by Django 5.0.1 on 2024-01-31 12:26

import analyses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assemblyanalysisrequest",
            name="request_metadata",
            field=models.JSONField(
                blank=True,
                default=analyses.models.AssemblyAnalysisRequest.RequestMetadata.default_metadata,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assemblyanalysisrequest",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analyses.study",
            ),
        ),
    ]
