# Generated by Django 5.0.1 on 2024-03-14 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="accession",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="accession",
        ),
        migrations.RemoveField(
            model_name="study",
            name="accession",
        ),
    ]
