# Generated by Django 5.0.1 on 2024-03-14 11:41
import analyses.base_models.mgnify_accessioned_models
import analyses.models
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0002_remove_analysis_accession_remove_sample_accession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="accession",
            field=analyses.base_models.mgnify_accessioned_models.MGnifyAccessionField(
                accession_length=8,
                accession_prefix="MGYA",
                db_index=True,
                db_persist=True,
                expression=analyses.base_models.mgnify_accessioned_models.ConcatOp(
                    models.Value("MGYA"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            models.F("id"), models.CharField()
                        ),
                        8,
                        models.Value("0"),
                    ),
                ),
                output_field=models.CharField(max_length=14),
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="accession",
            field=analyses.base_models.mgnify_accessioned_models.MGnifyAccessionField(
                accession_length=8,
                accession_prefix="MGYS",
                db_index=True,
                db_persist=True,
                expression=analyses.base_models.mgnify_accessioned_models.ConcatOp(
                    models.Value("MGYS"),
                    django.db.models.functions.text.LPad(
                        django.db.models.functions.comparison.Cast(
                            models.F("id"), models.CharField()
                        ),
                        8,
                        models.Value("0"),
                    ),
                ),
                output_field=models.CharField(max_length=14),
                unique=True,
            ),
        ),
    ]
