# Generated by Django 5.0.1 on 2024-01-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0002_alter_assemblyanalysisrequest_request_metadata_and_more"),
        ("ena", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="ena_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ena.study",
            ),
        ),
    ]
