# Generated by Django 5.0.1 on 2024-03-14 11:42

from django.db import migrations, models


def accessionise_fk(apps, schema_editor):
    Analysis = apps.get_model("analyses", "analysis")
    Study = apps.get_model("analyses", "study")

    for analysis in Analysis.objects.all():
        # associate the instance with corresponding Study's 'accession'
        study = Study.objects.get(id=analysis.study_id)
        analysis.study_via_accession = study
        analysis.save()


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0003_analysis_accession_study_accession"),
    ]

    operations = [
        # temp field for relationship of analysis to study via study accession
        migrations.AddField(
            model_name="analysis",
            name="study_via_accession",
            field=models.ForeignKey(
                null=True,
                on_delete=models.CASCADE,
                to="analyses.study",
                to_field="accession",
            ),
        ),
        migrations.RunPython(
            code=accessionise_fk, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="study",
        ),
        migrations.RenameField(
            model_name="analysis",
            old_name="study_via_accession",
            new_name="study",
        ),
        migrations.AlterField(
            model_name="analysis",
            name="study",
            field=models.ForeignKey(
                on_delete=models.CASCADE, to="analyses.study", to_field="accession"
            ),
        ),
    ]
