# Generated by Django 5.0.4 on 2024-04-25 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0004_alter_analysis_study"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name_plural": "Analyses"},
        ),
    ]
