# Generated by Django 5.0.4 on 2024-05-15 12:40

import django.db.models.deletion
from django.db import migrations, models

import analyses.models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0005_alter_analysis_options"),
        ("ena", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_ready", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "webin_submitter",
                    models.CharField(
                        blank=True, db_index=True, max_length=25, null=True
                    ),
                ),
                ("ena_accessions", models.JSONField(db_index=True, default=list)),
                ("is_suppressed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment_type",
                    models.CharField(
                        choices=[
                            ("METAT", "Metatranscriptomic"),
                            ("METAG", "Metagenomics"),
                            ("AMPLI", "Amplicon"),
                            ("ASSEM", "Assembly"),
                            ("HYASS", "Hybrid assembly"),
                            ("LRASS", "Long-read assembly"),
                            ("METAB", "Metabarcoding"),
                            ("UNKNO", "Unknown"),
                        ],
                        default="UNKNO",
                        max_length=5,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.JSONField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "ena_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ena.study"
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="analyses.study",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
