# Generated by Django 5.0.4 on 2024-05-16 13:27

import analyses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0006_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblies",
                to="analyses.run",
            ),
        ),
        migrations.AddField(
            model_name="assembly",
            name="status",
            field=models.JSONField(
                blank=True,
                default=analyses.models.Assembly.AssemblyStates.default_status,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="dir",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
