# Generated by Django 5.0.4 on 2024-06-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0007_assembly_run_assembly_status_alter_assembly_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="analyses.sample",
            ),
        ),
    ]
