# Generated by Django 5.0.4 on 2024-06-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0008_run_sample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="analyses.sample",
            ),
        ),
    ]
