# Generated by Django 5.0.4 on 2024-06-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0010_alter_study_options_alter_run_experiment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblies",
                to="analyses.study",
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="ena_accessions",
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name="run",
            name="ena_accessions",
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name="sample",
            name="ena_accessions",
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
        migrations.AlterField(
            model_name="study",
            name="ena_accessions",
            field=models.JSONField(blank=True, db_index=True, default=list),
        ),
    ]
