# Generated by Django 5.0.4 on 2024-06-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0011_assembly_study_alter_assembly_ena_accessions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblies",
                to="analyses.study",
            ),
        ),
    ]
