# Generated by Django 5.0.4 on 2024-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0012_alter_assembly_study"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assembly",
            options={"verbose_name_plural": "Assemblies"},
        ),
    ]
