# Generated by Django 5.0.4 on 2024-07-25 14:04

import django_ltree.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0015_alter_assembler_name"),
        ("django_ltree", "0001_create_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Biome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", django_ltree.fields.PathField(unique=True)),
                ("biome_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ("path",),
                "abstract": False,
            },
        ),
    ]
