# Generated by Django 5.0.4 on 2024-07-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0016_biome"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputeResourceHeuristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "process",
                    models.CharField(
                        blank=True,
                        choices=[("ASSEM", "Assembly")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("memory_gb", models.FloatField(blank=True, null=True)),
                (
                    "assembler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.assembler",
                    ),
                ),
                (
                    "biome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analyses.biome",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
