# Generated by Django 5.0.4 on 2024-07-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0017_computeresourceheuristic"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="biome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analyses.biome",
            ),
        ),
    ]
