# Generated by Django 5.0.4 on 2024-08-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0018_study_biome"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="pipeline_version",
            field=models.CharField(
                choices=[("V5", "v5.0"), ("V6", "v6.0")], default="V6", max_length=5
            ),
        ),
    ]
