# Generated by Django 5.0.4 on 2024-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyses", "0020_remove_run_status_analysis_assembly_analysis_run_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="downloads",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
