# Generated by Django 5.0.4 on 2024-10-09 13:22
import logging

from django.db import migrations, models


def ensure_assembly_metadata_are_top_level_dicts(apps, schema_editor):
    Assembly = apps.get_model("analyses", "assembly")

    for assembly in Assembly.objects.all():
        if not assembly.metadata:
            assembly.metadata = {}
        elif type(assembly.metadata) is dict:
            continue
        else:
            logging.warning(
                f"Wrapping metadata of assembly {assembly} into a dict, with key 'OTHER'"
            )
            assembly.metadata = {"OTHER": assembly.metadata}
        assembly.save()


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0021_analysis_downloads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="metadata",
            field=models.JSONField(blank=True, db_index=True, default=dict),
        ),
        migrations.RunPython(
            code=ensure_assembly_metadata_are_top_level_dicts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
