# Generated by Django 5.1.2 on 2024-11-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0022_alter_assembly_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
