# Generated by Django 5.0.4 on 2024-11-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0023_alter_run_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="instrument_model",
            field=models.CharField(
                blank=True, db_column="instrument_model", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="instrument_platform",
            field=models.CharField(
                blank=True, db_column="instrument_platform", max_length=100, null=True
            ),
        ),
    ]
