# Generated by Django 5.1.2 on 2024-12-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0025_analysis_experiment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="quality_control",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
