# Generated by Django 5.1.2 on 2025-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0026_analysis_quality_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="has_legacy_data",
            field=models.BooleanField(
                default=False, help_text="If the study has legacy data (pre V6)"
            ),
        ),
    ]
