# Generated by Django 5.1.2 on 2025-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0027_study_has_legacy_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="title",
            field=models.CharField(max_length=4000),
        ),
    ]
