# Generated by Django 5.1.2 on 2025-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0028_alter_study_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="is_suppressed",
            field=models.BooleanField(default=False),
        ),
    ]
