# Generated by Django 5.1.6 on 2025-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0030_alter_assembler_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
