# Generated by Django 5.1.6 on 2025-03-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0031_analysis_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assembly",
            options={"ordering": ["id"], "verbose_name_plural": "Assemblies"},
        ),
    ]
