# Generated by Django 5.1.6 on 2025-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0033_study_results_dir_alter_analysis_results_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="downloads",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
