# Generated by Django 5.1.6 on 2025-03-14 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0034_study_downloads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="watchers",
            field=models.ManyToManyField(
                related_name="studies_watching", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
