# Generated by Django 5.1.6 on 2025-03-19 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0035_study_watchers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="studies_watching", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
