# Generated by Django 5.1.6 on 2025-04-02 10:07
from typing import TYPE_CHECKING

from django.db import migrations, models

if TYPE_CHECKING:
    from analyses import models as mg_models


def associate_samples_with_studies(apps, schema_editor):
    Sample: "mg_models.Sample" = apps.get_model("analyses", "Sample")
    for sample in Sample.objects.all():
        if sample.runs:
            for run in sample.runs.all():
                sample.studies.add(run.study)
                print(f"Added study {run.study} to {sample}")


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0037_alter_analysis_results_dir_alter_study_results_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="studies",
            field=models.ManyToManyField(to="analyses.study"),
        ),
        migrations.RunPython(
            code=associate_samples_with_studies,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
