# Generated by Django 5.1.6 on 2025-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0038_sample_studies"),
        ("ena", "0004_alter_sample_additional_accessions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="is_ready",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="is_ready",
        ),
        migrations.RemoveField(
            model_name="study",
            name="is_ready",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="is_ready",
        ),
        migrations.AddField(
            model_name="analysis",
            name="is_ready",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Func(
                    models.Value("analysis_annotations_imported"),
                    function="jsonb_extract_path_text",
                    template="(jsonb_extract_path_text(status, %(expressions)s)::boolean)",
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                condition=models.Q(("is_ready", True), ("is_suppressed", False)),
                fields=["is_ready", "is_suppressed"],
                name="idx_ready_and_not_suppressed",
            ),
        ),
    ]
