# Generated by Django 5.2 on 2025-04-29 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


def copy_data_to_new_field(apps, schema_editor):
    """
    Copy data from the old JSONField to the new ArrayField.
    """
    Assembly = apps.get_model("analyses", "Assembly")
    Run = apps.get_model("analyses", "Run")
    Sample = apps.get_model("analyses", "Sample")
    Study = apps.get_model("analyses", "Study")

    for model in [Assembly, Run, Sample, Study]:
        for instance in model.objects.all():
            # Copy data from ena_accessions to ena_accessions_new
            instance.ena_accessions_new = instance.ena_accessions
            instance.save(update_fields=["ena_accessions_new"])


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0043_convert_ena_accessions_to_array"),
    ]

    operations = [
        # Step 1: Add new ArrayField columns
        migrations.AddField(
            model_name="assembly",
            name="ena_accessions_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20),
                blank=True,
                db_index=True,
                size=None,
                default=list,
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="ena_accessions_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20),
                blank=True,
                db_index=True,
                size=None,
                default=list,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="ena_accessions_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20),
                blank=True,
                db_index=True,
                size=None,
                default=list,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="ena_accessions_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20),
                blank=True,
                db_index=True,
                size=None,
                default=list,
            ),
        ),
        # Step 2: Copy data from old field to new field
        migrations.RunPython(copy_data_to_new_field, migrations.RunPython.noop),
        # Step 3: Remove old JSONField columns
        migrations.RemoveField(
            model_name="assembly",
            name="ena_accessions",
        ),
        migrations.RemoveField(
            model_name="run",
            name="ena_accessions",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="ena_accessions",
        ),
        migrations.RemoveField(
            model_name="study",
            name="ena_accessions",
        ),
        # Step 4: Rename new fields to original names
        migrations.RenameField(
            model_name="assembly",
            old_name="ena_accessions_new",
            new_name="ena_accessions",
        ),
        migrations.RenameField(
            model_name="run",
            old_name="ena_accessions_new",
            new_name="ena_accessions",
        ),
        migrations.RenameField(
            model_name="sample",
            old_name="ena_accessions_new",
            new_name="ena_accessions",
        ),
        migrations.RenameField(
            model_name="study",
            old_name="ena_accessions_new",
            new_name="ena_accessions",
        ),
    ]
