# Generated by Django 5.2 on 2025-05-01 14:38

import django.db.models.deletion
from django.db import migrations, models


def attach_sample_to_assembly(apps, schema_editor):
    """
    Attaches the Sample for each Assembly to it, by inheriting the Sample from the Run.
    """
    Assembly = apps.get_model("analyses", "Assembly")

    # Get all assemblies
    assemblies = Assembly.objects.all()

    # For each assembly with a run, set its sample to the run's sample
    for assembly in assemblies:
        if assembly.run and assembly.run.sample:
            assembly.sample = assembly.run.sample
            assembly.save()


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0044_alter_assembly_ena_accessions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assembly",
            name="sample",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblies",
                to="analyses.sample",
            ),
        ),
        migrations.RunPython(
            attach_sample_to_assembly,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
