# Generated by Django 5.2.1 on 2025-06-30 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0045_assembly_sample"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who will get notifications for this object",
                related_name="studies_watching",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
