# Generated by Django 5.0.3 on 2024-04-22 15:32

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrefectInitiatedHPCJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prefect_flow_run_id", models.UUIDField(db_index=True)),
                ("cluster_job_id", models.IntegerField(db_index=True)),
                ("command", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "last_known_state",
                    models.CharField(
                        choices=[
                            ("PREC", "Not yet submitted to cluster"),
                            ("PEND", "Pending on cluster"),
                            ("RUN", "Running on cluster"),
                            ("SUCC", "Completed in good state on cluster"),
                            ("FAIL", "Completed in a failed state on cluster"),
                        ],
                        default="PREC",
                        max_length=4,
                    ),
                ),
            ],
        ),
    ]
