# Generated by Django 5.0.4 on 2024-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prefectinitiatedhpcjob",
            options={
                "verbose_name": "Prefect Initiated HPC Job",
                "verbose_name_plural": "Prefect Initiated HPC Jobs",
            },
        ),
        migrations.AlterField(
            model_name="prefectinitiatedhpcjob",
            name="cluster_job_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
