# Generated by Django 5.0.4 on 2024-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_alter_prefectinitiatedhpcjob_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrefectInitiatedHPCJob",
        ),
    ]
