# Generated by Django 5.1.2 on 2025-01-13 12:11

import uuid

from django.db import migrations, models

import emgapiv2.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflows", "0003_delete_prefectinitiatedhpcjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrchestratedClusterJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cluster_job_id", models.IntegerField(db_index=True)),
                ("flow_run_id", models.UUIDField(db_index=True)),
                ("job_submit_description", emgapiv2.model_utils.JSONFieldWithSchema()),
                ("input_files_hashes", emgapiv2.model_utils.JSONFieldWithSchema()),
                (
                    "last_known_state",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("PENDING", "pending"),
                            ("RUNNING", "running"),
                            ("COMPLETING", "completing"),
                            ("COMPLETED", "completed"),
                            ("FAILED", "failed"),
                            ("TERMINATED", "terminated"),
                            ("SUSPENDED", "suspended"),
                            ("STOPPED", "stopped"),
                            ("TIMEOUT", "timeout"),
                            ("CANCELLED", "cancelled"),
                            ("OUT_OF_MEMORY", "out_of_memory"),
                            ("UNKNOWN", "unknown"),
                        ],
                        db_index=True,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "state_checked_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "nextflow_trace",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("cluster_log", models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
