# Generated by Django 5.1.2 on 2025-01-15 18:15

from django.db import migrations

import emgapiv2.model_utils
import workflows.models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0004_orchestrated_cluster_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orchestratedclusterjob",
            name="input_files_hashes",
            field=emgapiv2.model_utils.JSONFieldWithSchema(
                is_list=True,
                schema=workflows.models.OrchestratedClusterJob.JobInputFile,
                strict=False,
            ),
        ),
        migrations.AlterField(
            model_name="orchestratedclusterjob",
            name="job_submit_description",
            field=emgapiv2.model_utils.JSONFieldWithSchema(
                is_list=False,
                schema=workflows.models.OrchestratedClusterJob.SlurmJobSubmitDescription,
                strict=False,
            ),
        ),
    ]
