# Generated by Django 5.1.2 on 2025-01-16 14:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0005_alter_orchestratedclusterjob_input_files_hashes_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orchestratedclusterjob",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["job_submit_description"], name="workflows_o_job_sub_fbd723_gin"
            ),
        ),
    ]
