# Generated by Django 5.1.2 on 2025-01-16 17:06

from django.db import migrations

import emgapiv2.model_utils
import workflows.models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0006_orchestratedclusterjob_workflows_o_job_sub_fbd723_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orchestratedclusterjob",
            name="input_files_hashes",
            field=emgapiv2.model_utils.JSONFieldWithSchema(
                blank=True,
                default=list,
                encoder=emgapiv2.model_utils._PydanticEncoder,
                is_list=True,
                schema=workflows.models.OrchestratedClusterJob.JobInputFile,
                strict=False,
            ),
        ),
    ]
