# Generated by Django 5.0.4 on 2024-06-06 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ena", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"verbose_name_plural": "studies"},
        ),
    ]
