# Generated by Django 5.1.2 on 2025-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ena", "0002_alter_study_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="study",
            name="is_suppressed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="study",
            name="webin_submitter",
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True),
        ),
    ]
