# Generated by Django 5.1.6 on 2025-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ena", "0003_study_is_private_study_is_suppressed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="additional_accessions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="study",
            name="additional_accessions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
