_INSDC_CENTRE_PREFIXES = "EDS"

INSDC_STUDY_ACCESSION_REGEX: str = f"([{_INSDC_CENTRE_PREFIXES}]RP[0-9]{{6,}})"
INSDC_STUDY_ACCESSION_GLOB: str = f"[{_INSDC_CENTRE_PREFIXES}]RP[0-9]*"

INSDC_PROJECT_ACCESSION_REGEX: str = "(PRJ[NED][AB][0-9]+)"  # PRJNA, PRJEB, PRJDB
INSDC_PROJECT_ACCESSION_GLOB: str = "PRJ[NED][AB][0-9]*"

ENA_ASSEMBLY_ACCESSION_REGEX: str = f"([{_INSDC_CENTRE_PREFIXES}]RZ[0-9]{{6,}})"
ENA_ASSEMBLY_ACCESSION_GLOB: str = f"[{_INSDC_CENTRE_PREFIXES}]RZ[0-9]*"
