---
apiVersion: batch/v1
kind: Job
metadata:
  name: ebi-wp-k8s-hl-emgapi-migrate
  namespace: emgapiv2-hl-exp
spec:
  template:
    spec:
      containers:
        - name: run-migrations
          image: quay.io/microbiome-informatics/emgapiv2:ebi-wp-k8s-hl
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: emgapi-secret
            - configMapRef:
                name: emgapi-config
            - configMapRef:
                name: proxy-config
      restartPolicy: OnFailure
